#!/usr/bin/env bash
# Creates an nginx web sever
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee -a /var/www/html/index.html
sudo service nginx restart
