#!/usr/bin/env bash
# Reconfigure a web02 and managa a custom header

sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/ebukaejie/html
sudo echo "Hello World!" | sudo tee -a /var/www/ebukaejie/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee -a /var/www/ebukaejie/html/custom_404.html

sudo rm -rf /etc/nginx/sites-available/*
sudo rm -rf /etc/nginx/sites-enabled/*

sudo echo "server {
  listen 80;
  listen [::]:80 default_server;
  root /var/www/ebukaejie/html;
  index index.html;
  server_name ebukaejie.tech www.ebukaejie.tech;
  rewrite ^/redirect_me$ http://example.com/ permanent;
  error_page 404 /custom_404.html;
  location / {
    add_header X-Served-By $HOSTNAME;
  }
  
}" | sudo tee -a /etc/nginx/sites-available/ebukaejie.config

sudo ln -s /etc/nginx/sites-available/ebukaejie.config /etc/nginx/sites-enabled/

sudo service nginx restart
