#!/usr/bin/env bash
# Install a load balancer

# enable dedicated PPA
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
# install haproxy
sudo apt-get update -y
sudo apt-get install haproxy=2.7.\* -y
# enabling haproxy
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# new brand haproxy loadbalancer
sudo echo "listen www
global
    user haproxy
    group haproxy
frontend ebukaejie.tech
    bind *:80
    default_backend web_servers
backend web_servers
    balance roundrobin
    cookie SERVERUSED insert indirect nocache
    mode http
    option httpchk HEAD /
    default-server check maxconn 20
    server 138292-web-01 34.234.193.108:80 check
    server 138292-web-02 54.165.46.2:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
