#!/usr/bin/env bash
# Install a load balancer

# enable dedicated PPA
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
# install haproxy
sudo apt-get update -y
sudo apt-get install -y haproxy=2.0.\*
# enabling haproxy
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# new brand haproxy loadbalancer
sudo echo -e "
frontend load_balancer
\tbind *:80
\tmode http
\tdefault_backend webserver
backend webserver
\tbalance roundrobin
\tserver 138292-web-01 34.234.193.108:80 check
\tserver 138292-web-02 54.165.46.2:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
